version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: "fd00:ffff::/80"
